FROM node:12.10.0-alpine

# Add yarn
RUN apk update && apk add yarn
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy dependencies
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock

# Install dependencies
RUN yarn install

# Copy files
COPY . /app

# Build the app
CMD ['yarn', 'build']
